### ISSUE TITLE
Cant scan QR code - No Autofocus (Lineageos / AOSP)

### ISSUE THREAD

**Issue by bartman081523** [Digitaler-Impfnachweis/covpass-android#114]
## Avoid duplicates
* [ X ] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [ X ] Bug is not already reported in another issue

## Technical details

- Device name: SM-G900F
- OS version: LineageOS 7.1.2
- App version: 1.13.2

## Describe the bug

Not able to scan the code. 
Camera does not auto-focus in Android CovPass Check App when scanning the code. 
In other Apps (like CWA or Camera) the Camera auto-focuses without problem.

## Steps to reproduce the issue
Install the App on Android 7.1.2 and try to scan a code

## Expected behaviour

Camera autofocuses when scanning the code.
## Possible Fix

Continously - or tap-to-focus -autofocus the camera when scanning.
## Additional context
Section:Tap-To-Focus
https://proandroiddev.com/android-camerax-tap-to-focus-pinch-to-zoom-zoom-slider-eb88f3aa6fc6

https://gist.github.com/husaynhakeem/1eec93bc18ff863ae84c0acb6d406ac8#file-camerax_tap_to_focus-kt

**Comment by oltdaniel** [comment]
Can confirm this issue with the same device (`SM-G900F`) with Lineage OS `18.1` running Android 11. Normal autofocus in the Camera App or even the Corona Warn App do work.

**Comment by oltdaniel** [comment]
I've implemented a fix using the android developers documentation on the Control Focus topic, see https://github.com/oltdaniel/covpass-android/commit/e4efbbc7141fc2bcf7cfe3698f28c279472f4643 .

**Comment by chlorophyll-zz** [comment]
> I've implemented a fix using the android developers documentation on the Control Focus topic, see [oltdaniel@e4efbbc](https://github.com/oltdaniel/covpass-android/commit/e4efbbc7141fc2bcf7cfe3698f28c279472f4643) .
> 
> _Edit_: On tap focus has been added as well in [oltdaniel@13fd5ee](https://github.com/oltdaniel/covpass-android/commit/13fd5ee7bb909c65cc53c9a5648dc12bd110727f) .

Great! Awesome. Can you send me the apk to test? 
Or should i assemble it myself from source?

**Comment by oltdaniel** [comment]
> > I've implemented a fix using the android developers documentation on the Control Focus topic, see [oltdaniel@e4efbbc](https://github.com/oltdaniel/covpass-android/commit/e4efbbc7141fc2bcf7cfe3698f28c279472f4643) .
> > _Edit_: On tap focus has been added as well in [oltdaniel@13fd5ee](https://github.com/oltdaniel/covpass-android/commit/13fd5ee7bb909c65cc53c9a5648dc12bd110727f) .
> 
> Great! Awesome. Can you send me the apk to test? Or should i assemble it myself from source?

Do you trust a stranger from the Internet with giving you a random APK? I wouldn't.

**Comment by chlorophyll-zz** [comment]
Just gimme the apk, yes

**Comment by chlorophyll-zz** [comment]
> 



>

**Comment by chlorophyll-zz** [comment]
> > > I've implemented a fix using the android developers documentation on the Control Focus topic, see [oltdaniel@e4efbbc](https://github.com/oltdaniel/covpass-android/commit/e4efbbc7141fc2bcf7cfe3698f28c279472f4643) .
> > > _Edit_: On tap focus has been added as well in [oltdaniel@13fd5ee](https://github.com/oltdaniel/covpass-android/commit/13fd5ee7bb909c65cc53c9a5648dc12bd110727f) .
> > 
> > 
> > Great! Awesome. Can you send me the apk to test? Or should i assemble it myself from source?
> 
> Do you trust a stranger from the Internet with giving you a random APK? I wouldn't.

I have no problem with that. If I where paranoid, I know how to use virustotal.

**Comment by chlorophyll-zz** [comment]
Now you have to wait for my Intel Core 2 Duo to assmble the App, before I close the Issue. 
If you have given me the apk, I would have verified and closed right away.

**Comment by chlorophyll-zz** [comment]
[X] Verified: Your Commit enables scanning with auto-focus and tap-to-focus on our Device (SM-G900F - Samsung Galaxy S5).
Probably fixes for any other device that does not auto-focus by itself. 

@oltdaniel excuse my tone before, this was not my best day.

**Comment by chlorophyll-zz** [comment]
In the meantime please use the Austrian GreenCheck App https://greencheck.gv.at/ it has continous auto-focus and tap-to-focus.

**Comment by beevelop** [comment]
Issue can currently be reproduced on a SM-G900F with Android `6.0.1` and app version `1.13.2`

**Comment by rhurlin** [comment]
Thank you very much for the patch!

I have exactly the described problem with a Samsung Galaxy SM-J500FN from 2015, Android OS version 6.0.1. App version here is also 1.13.2

Until a few weeks ago, scanning QR codes on this device with the CovPass app still worked, older vaccination certificates have already been scanned.  The fact that the autofocus no longer works is definitely due to the CovPass app. With other apps, QR code scanning on this device still works as expected.

For older devices like the SM-J500FN the app is no longer usable, a merge of this patch would be very important :)

**Comment by jleufgen** [comment]
@chlorophyll-zz thanks for the hint. We are working on the topic. In one of the next releases this bug should be fixed.

**Comment by HagenSdt** [comment]
Workaround for now: I did a normal photo of the QR code, increased the size to full screen on my monitor and used the CovPass app to scan it from my monitor.

**Comment by rhurlin** [comment]
> Workaround for now: I did a normal photo of the QR code, increased the size to full screen on my monitor and used the CovPass app to scan it from my monitor.

Hi @HagenSdt,
Thank you for this workaround. I tried it and it worked right away!   \o/

Now we have at least a few months to wait for the commit of the patch for autofocus. And my 2015 device doesn't have to be retired yet. That would be a shame too, since it works fine :)

**Comment by chlorophyll-zz** [comment]
@rhurlin @HagenSdt
I builded a unsigned debug apk from @oltdaniel s PR #125 for you and everyone affected so you dont have to use a workaround. 

This (private- unsigned- debug-) "pre-release" has working initial focus when you open the scanner and working tap-to-focus when you tap the camera window in the scanner. 

I am not saying that you should use it or that you have to trust the file. 
But it worked very well on my Galaxy S5. 
You can see yourself the results 0/59 on Virustotal and that the sha256sum match or upload the apk there yourself. 

Download (Google Drive): 
https://drive.google.com/file/d/1F94JTHjvmnCoUPObnrP8IPx2BOxHiLp5/view?usp=sharing
md5sum: 1b8b82d236751d1044c7f44de07ffe73

Virustotal: 
https://www.virustotal.com/gui/file-analysis/MWI4YjgyZDIzNjc1MWQxMDQ0YzdmNDRkZTA3ZmZlNzM6MTYzOTg1MDM0MA==

sha256sum:
098b10d1be4d98ab2fae05c4c448b35a48a95a85569f65a674a8b0e7a121a0d0  ./covpass-android/app-covpass-check-prod/build/outputs/apk/debug/covpasscheckprod-1.12.0-1.216.1-feature-fix-autofocus-SNAPSHOT-debug.apk

**Comment by KBrand101** [comment]
@jleufgen Can you approximately say which release will incorporate the fix and when we can expect it? Is it worth waiting for an update of the official app or will I need to build it myself?

The affected device is the same as @beevelop mentioned, but the app version is `1.13.3`:
> Issue can currently be reproduced on a SM-G900F with Android `6.0.1` and app version `1.13.2`

**Comment by jleufgen** [comment]
In the next release the bug should be fixed @KBrand101 :)

**Comment by rhurlin** [comment]
> In the next release the bug should be fixed @KBrand101 :)

Nice to hear, thanks a lot!

**Comment by thomaszbz** [comment]
One more confirmation with autofocus not working:

- Device name: SM-G900F
- OS version: LineageOS 16.0, Android 9
- App version: 1.15.0

**Comment by rhurlin** [comment]
Just a small feedback after the last update:
Since v1.15.0 the app works again on Samsung Galaxy SM-J500FN from 2015 with Android OS version 6.0.1.
Many thanks!  \o/

**Comment by pucherd** [comment]
Hello @chlorophyll-zz, the bug should be fixed with your latest 1.16.1 release.

**Comment by Art4** [comment]
> the bug should be fixed with our latest 1.16.1 release.

When will version 1.16.1 be released?

**Comment by Ein-Tim** [comment]
@Art4 Version 1.16 is in the Google Play Store already.

**Comment by Art4** [comment]
> Version 1.16.1 is in the Google Play Store already.

Is there a public way to see which versions have been released? The releases and git tags in this repo are not up to date. And the Google Playstore still shows me 1.15.0.

https://play.google.com/store/apps/details?id=de.rki.covpass.checkapp

**Comment by pucherd** [comment]
@Art4 CovPass 1.16.1 is release but CovPassCheck is still in review - will be released soon.

**Comment by HagenSdt** [comment]
Autofocus is now working on my SM-G900F. Thanks a lot for the update.

**Comment by thomaszbz** [comment]
I Updated to App version 1.16.1, but still there is no autofocus.

    Device name: SM-G900F
    OS version: LineageOS 16.0, Android 9
    App version: 1.16.1

I do not have such problems in CWA.

I also rebooted with a deleted dalvik cache and cache. Still no autofocus.

**Comment by KBrand101** [comment]
I thankfully can report that it is working fine for me now since I updated to version `1.16.1`.
As said previously I'm using a `SM-G900F` which at the moment is running the stock Android `6.0.1`. 

@thomaszbz: In the current state the autofocus appears to be applied automatically and continously rather than by tapping the screen. I also didn't need to change any configuration or clear any cache. It basically just worked.

**Comment by Ein-Tim** [comment]
FYI it seems like this is a bug in LineageOS: https://gitlab.com/LineageOS/issues/android/-/issues/4189

**Comment by chlorophyll-zz** [comment]
Can confirm that continous auto-focus now works with CovPass Check v 1.16 on Lineageos 14.1 (Android 7.1.2)

Nevertheless, I will leave this open until Lineageos 18.1 is also in the "alternate auto-focus" whitelist.
https://github.com/Digitaler-Impfnachweis/covpass-android/pull/125

**Comment by chlorophyll-zz** [comment]
Can confirm that continous auto-focus now works with CovPass Check v 1.16 on Lineageos 14.1 (Android 7.1.2)
However, I will leave this open until the continuous auto-focus also works with Lineageos 18.1.
https://github.com/Digitaler-Impfnachweis/covpass-android/pull/125

**Comment by KrautHolg** [comment]
Same problem with SM-G900F Android Version 10 aosp_klte-userdebug 10 QQ3A.200705.002 1670e198 realease-keys

**Comment by chlorophyll-zz** [comment]
@KrautHolg @ossilator @thomaszbz 
You can clone this fork from @oltdaniel for yourself: https://github.com/oltdaniel/covpass-android/tree/feature/fix-autofocus and build the App on your computer, when you want a working (continous and tap-to-focus) autofocus before an update (and the developers are again failing to address your issue for *some* months, ignoring/regarding that the App is (state-sponsored (15.400.000€)) critical infrastructure):

Building the app
You'll need a GitHub personal access token with read:packages access: 
https://github.com/settings/tokens -  "Generate new token" - Select read:pacackages - create the token - reveal the token secret - copy the token secret.

and in the parent folder **above** your repository (covpass-android folder) create a file called covpass.properties:

```
git clone https://github.com/oltdaniel/covpass-android.git --branch feature/fix-autofocus
nano/Notepad covpass.properties
```
```
githubUsername=github-username
githubPassword=paste here your copied token secret
```

To actually build the app:

Install Android Studio:
https://developer.android.com/studio/install

Open the project/covpass-android folder with Android Studio. 
In the toolbar at the top, select the app you want to run (e.g. app-covpass-check) and the device.
Select Grade Build Flavour/Build Type "debug"
Connect your Device in ADB mode, select your Device next to the play button
Press the "play"/run button

**Comment by pucherd** [comment]
Hello @chlorophyll-zz,
The 1.16.1 version we released last week already contains the autofocus fix (continuous autofocus) which is based on the implementation you are referring to. 
Have you already tested if the autofocus works in Lineageos with https://github.com/oltdaniel/covpass-android/tree/feature/fix-autofocus fork?

**Comment by chlorophyll-zz** [comment]
@pucherd the fork works at least with 7.1.2. I dont know wether the fork also works with LOS 18.1, so the users could test the fork. 
And your fix does not support Lineageos 18 and 16 and AOSP 10. 
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/114#issuecomment-1017845881
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/114#issuecomment-1017560966
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/114#issuecomment-1022265683

**Comment by pucherd** [comment]
@chlorophyll-zz right but looks like the issue is in Lineageos:
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/114#issuecomment-1018648594

**Comment by chlorophyll-zz** [comment]
@pucherd that depends on the app. The camera app works as expected, like the issue on gitlab suggests and other apps like cwa and many other apps also work well with LOS 18.1. 
https://gitlab.com/LineageOS/issues/android/-/issues/4189
"
*Some* Apps can't use the autofocus function of the device's camera and therefore they can't scan QR-codes or other grafics, because they can't focus them. The ordinary camera App of the device can use the autofocus without a problem.
"

Which means the issue *could* be resolved by *this* app. So I am not closing this. 
The issue is not fixable on the LOS side for pre-18.1, because e.g. LOS 16 is EOL. And definately not fixable for the users of the devices running that OS.

**Comment by memartinb** [comment]
I can confirm this is still an issue with CovPass v1.27.0 (15 Jul 2022) on Samsung SM-G800F (S5 mini / kminilte) with LineageOS 16 (Android 9).

Corona Tracing App can scan Certificates fine, CovPass still can't. Camera opens up, but stutters badly and freezes after 3 refreshes. Might be a different problem, but I've had the focus problem with other Apps (DATEV SmartLogin, DHL App) where it was fixed on App level. So should defininitely be an issue with ensuring proper camera access.

I'd really like to use CovPass over the Tracing App, because Certificates is the only thing I use and CovPass would be more lightweight.

**Comment by bartman081523** [comment]
@pucherd I confirm autofocus is now working, I have version 1.32.0. 
From my view, issue seems fixed for LineageOS 14.1 / AOSP 7.1.2.

@KrautHolg @ossilator @thomaszbz could you test CovpassCheck above version 1.30 too on your devices? 
Then we can confirm alltogether for AOSP 9,10 and 11 a working autofocus.

**Comment by ossilator** [comment]
still doesn't work on my device. it clearly needs some Very Special Treatment (TM) (both the pre-installed camera app and opencamera can do it just fine, so it can't be *that* hard).

**Comment by bartman081523** [comment]
> still doesn't work on my device.
thats bad. I summarize: @pucherd Still no continuous autofocus on LineageOS 18.1 with Version >=1.30
@ossilator please correct me if I'm wrong.

**Comment by ossilator** [comment]
according to my research (which dates back quite some months), it's also specific to the device model (or more accurately, a bunch of models). i suppose it's an adverse interaction with the (proprietary) camera driver. see also the previously linked CWA issue.

**Comment by memartinb** [comment]
**Not** fixed for me (camera stutter) using v1.31.1.
Not seeing 1.32 yet. Will report.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
